# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debfb1ec3070e004a93ae80dce232ec13c8e5fa082d441ddc45a534700a556b5f65e0ac7d8a3800ea256c44d9816edceb7c807b243096fd5916f1389cc01668a

test:
  secret_key_base: 9d6e8e347dc66fbe284b70d9ee088434a1c262bd6b108f81aebf85400ada7dc2bd9858860a455d192078e96719f2b0b2ed4c8b61c7defc78c705f097a6c5bf7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
